language: objective-c
osx_image: xcode8
before_install: 
  - gem install scan
  - ls -la
before_script:
  - instruments -s devices
  - xcodebuild -version
  - xcodebuild -showsdks
script:
  - scan
after_success:
  - bash <(curl -s https://codecov.io/bash)